name: MenosCore
version: '${project.version}'
main: com.menosmc.menoscore.MenosCore
api-version: 1.20
authors: [ frikandelworst ]
description: The core plugin of MenosMC.
website: menosmc.com
depend:
  - LuckPerms
